[package]
authors = ["ZingerLittleBee"]
edition = "2021"
name = "ostat"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
systemstat = "0.1.11"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
